version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: vet_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vet_reservation
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_0900_ai_ci","--explicit_defaults_for_timestamp=ON","--default-time-zone=+09:00"]
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
